# This file defines the production settings. It is overwritten by docker-compose.override.yml,
# which defines the development settings. The override.yml is loaded by default. Therefore it
# is required to explicitly define if you want an production build:
# > docker-compose -f docker-compose.yml up 

version: "3.4"

services:

  ########################################################
  # LOCALSTACK ###########################################
  ########################################################
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    networks:
      - external-net
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-central-1
      - SERVICES=s3
      - LOCALSTACK_HOST=localstack:4566
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./localstack.sh:/etc/localstack/init/ready.d/localstack.sh

  ########################################################
  # WEBAPP ###############################################
  ########################################################
  webapp:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: ocelotsocialnetwork/webapp:local-development
    container_name: webapp
    build:
      context: ./webapp
      target: development
    networks:
      - external-net
    depends_on:
      - backend
    ports:
      - 3000:3000
      # Storybook: Todo externalize, its not working anyways
      # - 3002:3002
    environment:
      # Envs used in Dockerfile
      # - DOCKER_WORKDIR="/app"
      # - PORT="3000"
      - BUILD_DATE
      - BUILD_VERSION
      - BUILD_COMMIT
      # Application only envs
      - HOST=0.0.0.0 # This is nuxt specific, alternative value is HOST=webapp
      - GRAPHQL_URI=http://backend:4000
      - NODE_ENV="development"
      # - DEBUG=true
      - NUXT_BUILD=/tmp/nuxt # avoid file permission issues when `rm -rf .nuxt/`
    env_file:
      - ./webapp/.env
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - webapp_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./webapp:/app
  ########################################################
  # BACKEND ##############################################
  ########################################################
  backend:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: ocelotsocialnetwork/backend:local-development
    container_name: backend
    build:
      context: ./backend
      target: development
    networks:
      - external-net
      - internal-net
    depends_on:
      - neo4j
      - localstack
    ports:
      - 4000:4000
    volumes:
      - backend_uploads:/app/public/uploads
      # Therefore it is possible to have a different node version on the host machine
      - backend_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./backend:/app
    environment:
      # Envs used in Dockerfile
      # - DOCKER_WORKDIR="/app"
      # - PORT="4000"
      - BUILD_DATE
      - BUILD_VERSION
      - BUILD_COMMIT
      - NODE_ENV="production"
      # Application only envs
      - DEBUG=false
      - NEO4J_URI=bolt://neo4j:7687
      - GRAPHQL_URI=http://backend:4000
      - CLIENT_URI=http://webapp:3000
    env_file:
      - ./backend/.env

  ########################################################
  # MAINTENANCE ##########################################
  ########################################################
  maintenance:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: ocelotsocialnetwork/maintenance:local-development
    container_name: maintenance
    build:
      # TODO: Separate from webapp, this must be independent
      context: ./webapp
      dockerfile: Dockerfile.maintenance
    networks:
      - external-net
    ports:
      - 3001:80

  ########################################################
  # NEO4J ################################################
  ########################################################
  neo4j:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: ocelotsocialnetwork/neo4j-community:local-development
    container_name: neo4j
    build:
      context: ./neo4j
      # community edition 👆🏼, because we have no enterprise licence 👇🏼 at the moment
      target: community
    networks:
      - internal-net
    ports:
      - 7687:7687
    volumes:
      - neo4j_data:/data
    environment:
      # settings reference: https://neo4j.com/docs/operations-manual/4.4/docker/ref-settings/
      # TODO: This sounds scary for a production environment
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_procedures_unrestricted=algo.*,apoc.*
      - NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_allow__upgrade=true
      # Uncomment following line for Neo4j Enterprise version instead of Community version
      # TODO: clarify if that is the only thing needed to unlock the Enterprise version
      # - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # TODO: Remove the playground from production
    # bring the database in offline mode to export or load dumps
    # command: ["tail", "-f", "/dev/null"]

  ########################################################
  # MAILSERVER TO FAKE SMTP ##############################
  ########################################################
  mailserver:
    image: djfarrelly/maildev
    container_name: mailserver
    ports:
      - 1080:80
    networks:
      - external-net

networks:
  external-net:
  internal-net:
    internal: true

volumes:
  webapp_node_modules:
  backend_uploads:
  neo4j_data:
  backend_node_modules:
